//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Commerce_Pet_Store
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShoppingCart
    {
        public int CartId { get; set; }
        public Nullable<int> UserId { get; set; }
        public int ProductID { get; set; }
        public Nullable<System.DateTime> DatePurchased { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public Nullable<int> Duration { get; set; }
        public Nullable<double> TotalCost { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual User User { get; set; }
    }
}
